// User
export const ERROR_RECEIVE_USER = 'ERROR_RECEIVE_USER';
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';

export const ERROR_SIGN_IN = 'ERROR_SIGN_IN';
export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const SUCCESS_SIGN_IN = 'SUCCESS_SIGN_IN';

export const ERROR_SIGN_UP = 'ERROR_SIGN_UP';
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const SUCCESS_SIGN_UP = 'SUCCESS_SIGN_UP';

export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT';

export const REQUEST_PURCHASE_RECORDS = 'REQUEST_PURCHASE_RECORDS';
export const RECEIVE_PURCHASE_RECORDS = 'RECEIVE_PURCHASE_RECORDS';
export const ERROR_PURCHASE_RECORDS = 'ERROR_PURCHASE_RECORDS';
export const CLEAR_PURCHASE_RECORDS = 'CLEAR_PURCHASE_RECORDS';

export const REQUEST_DELETE_PURCHASE_RECORD = 'REQUEST_DELETE_PURCHASE_RECORD';

export const SUCCESS_DELETE_PURCHASE_RECORD = 'SUCCESS_DELETE_PURCHASE_RECORD';

export const ERROR_DELETE_PURCHASE_RECORD = 'ERROR_DELETE_PURCHASE_RECORD';

export const REQUEST_PURCHASE_RECORD = 'REQUEST_PURCHASE_RECORD';
export const RECEIVE_PURCHASE_RECORD = 'RECEIVE_PURCHASE_RECORD';
export const ERROR_PURCHASE_RECORD = 'ERROR_PURCHASE_RECORD';

export const REQUEST_PURCHASE_MATERIALS = 'REQUEST_PURCHASE_MATERIALS';
export const RECEIVE_PURCHASE_MATERIALS = 'RECEIVE_PURCHASE_MATERIALS';
export const ERROR_PURCHASE_MATERIALS = 'ERROR_PURCHASE_MATERIALS';

export const REQUEST_SAVE_PURCHASE_RECORD = 'REQUEST_SAVE_PURCHASE_RECORD';
export const SUCCESS_SAVE_PURCHASE_RECORD = 'SUCCESS_SAVE_PURCHASE_RECORD';
export const ERROR_SAVE_PURCHASE_RECORD = 'ERROR_SAVE_PURCHASE_RECORD';
